### ISSUE TITLE
VS express 2012

### ISSUE THREAD

**Issue by sinrise** [zeiban/defiance-tools#1]
Tried to run this and all it said was "unable to start program wadlib.lib"

**Comment by zeiban** [comment]
What command-line tool were you trying to run?

**Comment by sinrise** [comment]
The wadlib one, I think. I'm very new to this.

On Sunday, October 6, 2013, zeiban wrote:

> What command-line tool were you trying to run?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zeiban/defiance-tools/issues/1#issuecomment-25782133
> .

## 

-Ivan

**Comment by zeiban** [comment]
wadlib is just a library. It can't be run by its self. It used by all the the other tools to perform common tasks. If you just want to run the command-line tools you can download the binary releases on the [releases page](https://github.com/zeiban/defiance-tools/releases).

**Comment by sinrise** [comment]
Oh ok, great. Thanks! :)

-Ivan
